[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  external_node_modules = ["@netlify/neon"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Redirect all function calls to the correct path
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200